language: python
python:
  - "3.8"
jobs:
  include:
    - name: Check changed files
      stage: check
      if: type IN (pull_request)
      script:
        - echo "Check changed files"
        - env

    - name: Build image
      stage: build
      if: env(TRAVIS_BRANCH) = master AND (env(TRAVIS_BRANCH) = env(DIST_BRANCH)) AND type NOT IN (pull_request)
      script:
        - echo "Build image"
        - env
