name: Deploy
on:
  push:
    branches: [ master, main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment CI
        run: |
          /sbin/ip a
          curl -X POST --connect-timeout 20 -F "ref=master" -F token=$TRIGGER_TOKEN $PROJECT_URL
          if [ $? -ne 0 ] ; then echo "Failed to trigger pipeline"; fi
        env:
          TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
          PROJECT_URL: ${{ secrets.PROJECT_URL }}
