name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          GITLAB_PIPELINE_TRIGGER_TOKEN: ${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }}
        run: |
          curl --connect-timeout 20 https://gitlab.devops.ukfast.co.uk/api/v4/projects/2570/ref/master/trigger/pipeline?token=$GITLAB_PIPELINE_TRIGGER_TOKEN
          if [ $? -eq 0 ]; then echo "Successfully triggered pipeline"; else echo "Failed to trigger pipeline"; fi
        
