name: Check files

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    steps:
      - name: Check files
        runs-on: ubuntu-latest
        run: |
          echo "Check files"
          env

