name: Check files
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get All Changed Files
        uses: jitterbit/get-changed-files@v1
      - run: env | sort
      - run: ./tests.sh ${{ steps.files.outputs.all }}
      # - run: ./tests.sh
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'
      #     architecture: 'x64'
      # - run: |
      #     python -m pip install --upgrade pip
      #     pip install Sphinx recommonmark
          
